Num1 = int(input("Enter number 1:"))
Num2 = int(input("Enter number 3:"))
Num3 = int(input("Enter number 3:"))
Total = (Num1+Num2+Num3)
Average = (Total/3)
print ("The total is: ", Total, "\nThe average is ", Average,  sep='')